name: Flutter

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env.staging file
        run: |
          echo "ENVIRONMENT=${{ secrets.STAGING__ENVIRONMENT }}" >> .env.staging

      - name: Create .env.prod file
        run: |
          echo "ENVIRONMENT=${{ secrets.PROD__ENVIRONMENT }}" >> .env.prod

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed.
      - name: Run tests
        run: flutter test
